export const APP_CONSTANTS = {
  UNAUTHENTICATED: "Unauthenticated",
  BASIC_TIER: "basic",
  PRO_TIER: "pro",
  ENGLISH: "en",
  SUCCESS: "success",
  NAME_EMPTY: "Enter your name.",
  EMAIL_INVALID: "Enter a valid email address.",
  PASSWORD_LENGTH_SHORT: "Password must be at least 8 characters.",
  PASSWORD_MISMATCH: "Passwords do not match.",
  EMAIL_TAKEN: "This email is already taken.",
  TOO_MANY_ATTEMPTS: "Too many attempts. Try again later.",
  BAD_NETWORK: "Network error. Check your internet connection and try again.",
  USER_DISABLED: "This email has been disabled.",
  INVALID_CREDENTIALS: "Wrong email or password.",
  UNKNOWN_ERROR: "An unknown error occurred. Try again later.",
};
